### ISSUE TITLE
missing env var _LAMBDA_SERVER_PORT causes crash

### ISSUE THREAD

**Issue by dsilvasc** [srijs/rust-aws-lambda#23]
When testing this library outside of Lambda (I was just testing to see if I could call it from the JVM via JNI), I got the following crash:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent

stack backtrace:
   0:     0x7fc4027104d5 - backtrace::backtrace::libunwind::trace::h87851776d7e1eb58
                        at target/cargo-linux/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hc7a02ea547227081
                        at target/cargo-linux/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x7fc40270b4fe - backtrace::capture::Backtrace::new_unresolved::h588c937f6ac1a876
                        at target/cargo-linux/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x7fc402709ed7 - failure::backtrace::internal::InternalBacktrace::new::h4b64c8d3b306570d
                        at target/cargo-linux/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/internal.rs:44
   3:     0x7fc402708ebc - failure::backtrace::Backtrace::new::h6347cf43cacf9204
                        at target/cargo-linux/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/mod.rs:98
   4:     0x7fc4024f2e2d - <failure::error::Error as core::convert::From<F>>::from::h23162f001edfbb07
                        at /usr/src/myapp/target/cargo-linux/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error.rs:34
   5:     0x7fc4024e869d - aws_lambda_runtime::runtime::Runtime::start_service::h5a7384eda6fb991b
                        at /usr/src/myapp/target/cargo-linux/git/checkouts/rust-aws-lambda-2a7b20b15eabd9cc/7952353/aws_lambda_runtime/src/runtime.rs:66
   6:     0x7fc4024e917b - aws_lambda_runtime::runtime::Runtime::start::hc30e0ea9f9a34b45
                        at /usr/src/myapp/target/cargo-linux/git/checkouts/rust-aws-lambda-2a7b20b15eabd9cc/7952353/aws_lambda_runtime/src/runtime.rs:52
   7:     0x7fc4024e938a - aws_lambda::start::h7c70481e7c7b4307
                        at /usr/src/myapp/target/cargo-linux/git/checkouts/rust-aws-lambda-2a7b20b15eabd9cc/7952353/aws_lambda/src/lib.rs:49
   8:     0x7fc40250efef - Java_snapchat_lambda_Bridge_start
                        at src/lib.rs:38
   9:     0x7fc40bf83406 - <unknown>', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: aws_lambda::start
             at /usr/src/myapp/target/cargo-linux/git/checkouts/rust-aws-lambda-2a7b20b15eabd9cc/7952353/aws_lambda/src/lib.rs:49
  11: Java_snapchat_lambda_Bridge_start
             at src/lib.rs:38
  12: <unknown>
fatal runtime error: failed to initiate panic, error 5
#
# A fatal error has been detected by the Java Runtime Environment:

#
#  SIGSEGV (0xb) at pc=0x00007fc42212c8f0, pid=1, tid=0x00007fc422907700
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x408f0]  abort+0x230
```

Looks like the error comes from `start_service` in aws_lambda_runtime/src/runtime.rs:

```rust
    /// Start the runtime with the given `Service`.
    pub fn start_service<S>(mut self, s: S) -> Result<(), Error>
    where
        S: NewService<Error = Error>,
        S::Instance: 'static,
        S::Request: DeserializeOwned + Send + 'static,
        S::Response: Serialize + Send + 'static,
    {
        let port = env::var("_LAMBDA_SERVER_PORT")?.parse()?;
        let addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), port);
        let handle = self.core.handle();
        let listener = TcpListener::bind(&addr, &handle)?;
        let server = Server::new(s, listener.incoming(), handle);
        self.core.run(server)?;
        Ok(())
    }
```

The first line of the function expects the environment variable _LAMBDA_SERVER_PORT to be defined, otherwise it returns Err and `start` in aws_lambda/src/lib.rs expects success:

```rust
pub fn start<F, R, S>(f: F)
where
    F: Fn(R) -> S + 'static,
    S: IntoFuture<Error = Error>,
    S::Item: Serialize + Send + 'static,
    R: DeserializeOwned + Send + 'static,
{
    Runtime::new().unwrap().start(f).unwrap()
}
```

Would it be possible for `start_service` to fall back on a default port number and/or for `start` to handle the error more gracefully?

**Comment by hazel-ocean** [comment]
If it's an environment variable, you could just set it yourself for testing purposes. Since it's controlled by the system and not something specified in the Go SDK (please correct me if I'm wrong on this), it might change out from under you in a production environment. It would be a sad thing for someone to be setting it manually to the whatever the current value is, then suddenly that number changes in the future and they have to go debug why their systems are suddenly panicking in production.

**Comment by LegNeato** [comment]
This is expected for the reasons @davidarmstronglewis mentions. Either set it manually or use something like https://github.com/awslabs/aws-sam-cli to test locally.

We should document it though.

**Comment by hazel-ocean** [comment]
What would be an appropriate way to document this?

**Comment by dsilvasc** [comment]
Would it help to add an `expect` call in `start_service` saying that _LAMBDA_SERVER_PORT is a required env variable?  And `expect` instead of `unwrap` in `start` to explain what's expected there.

**Comment by hazel-ocean** [comment]
Sounds like a great idea to panic with some kind of message. Made a PR.

**Comment by hazel-ocean** [comment]
@dsilvasc curious if you've had a time to revisit this.

**Comment by LegNeato** [comment]
Looks like @srijs just revamped error handling, closing.

**Comment by dsilvasc** [comment]
Requiring that the environment variable be present sounds reasonable.  Thanks for improving the error handling 👍
